/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.das.group.assignment.store;

import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.LinkedList;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author testing
 */
public class MyCart extends javax.swing.JFrame {

        /**
         * Creates new form MyCart
         */
        public MyCart() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                StoreBtn = new javax.swing.JButton();
                jPanel11 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                TotalPrcLble = new javax.swing.JLabel();
                jPanel12 = new javax.swing.JPanel();
                jLabel14 = new javax.swing.JLabel();
                PromoTextField = new javax.swing.JTextField();
                ApplyCodeBtn = new javax.swing.JButton();
                jPanel13 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                FnlPriceLble = new javax.swing.JLabel();
                CheckoutBtn = new javax.swing.JButton();
                JScroll1 = new javax.swing.JScrollPane();
                CartItemsPanel = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(815, 900));

                jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                jLabel1.setText("My Cart");

                StoreBtn.setText("STORE");
                StoreBtn.setToolTipText("");
                StoreBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                StoreBtnActionPerformed(evt);
                        }
                });

                jPanel11.setBackground(new java.awt.Color(255, 255, 255));

                jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel10.setText("Total Price ");

                TotalPrcLble.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                TotalPrcLble.setText("200 RM");

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(jPanel11Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel11Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel10).addGap(204, 204, 204).addComponent(TotalPrcLble)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                jPanel11Layout.setVerticalGroup(jPanel11Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout
                                                .createSequentialGroup().addContainerGap(17, Short.MAX_VALUE)
                                                .addGroup(jPanel11Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel10).addComponent(TotalPrcLble))
                                                .addGap(14, 14, 14)));

                jPanel12.setBackground(new java.awt.Color(255, 255, 255));

                jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel14.setText("Apply Promo Code");

                PromoTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

                ApplyCodeBtn.setText("Apply Code");
                ApplyCodeBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ApplyCodeBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(jPanel12Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel12Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel14).addGap(18, 18, 18)
                                                .addComponent(PromoTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ApplyCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 132,
                                                                Short.MAX_VALUE)
                                                .addGap(22, 22, 22)));
                jPanel12Layout.setVerticalGroup(jPanel12Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel12Layout.createSequentialGroup().addContainerGap(11, Short.MAX_VALUE)
                                                .addGroup(jPanel12Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel12Layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel14)
                                                                                                .addComponent(PromoTextField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                34,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(ApplyCodeBtn,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap()));

                jPanel13.setBackground(new java.awt.Color(255, 255, 255));

                jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                jLabel12.setText("Final Price");

                FnlPriceLble.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                FnlPriceLble.setText("100 RM");

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(jPanel13Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel13Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel12).addGap(215, 215, 215).addComponent(FnlPriceLble)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                jPanel13Layout.setVerticalGroup(jPanel13Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout
                                                .createSequentialGroup().addContainerGap(17, Short.MAX_VALUE)
                                                .addGroup(jPanel13Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel12).addComponent(FnlPriceLble))
                                                .addGap(14, 14, 14)));

                CheckoutBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                CheckoutBtn.setText("Checkout");
                CheckoutBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CheckoutBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout CartItemsPanelLayout = new javax.swing.GroupLayout(CartItemsPanel);
                CartItemsPanel.setLayout(CartItemsPanelLayout);
                CartItemsPanelLayout.setHorizontalGroup(
                                CartItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 617, Short.MAX_VALUE));
                CartItemsPanelLayout.setVerticalGroup(
                                CartItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 564, Short.MAX_VALUE));

                JScroll1.setViewportView(CartItemsPanel);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup().addContainerGap()
                                                                .addComponent(jPanel11,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup().addContainerGap()
                                                                .addComponent(jPanel12,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup().addContainerGap()
                                                                .addComponent(jPanel13,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup().addGap(33, 33, 33)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(StoreBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                173,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup().addContainerGap()
                                                                .addComponent(JScroll1))
                                                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(
                                                                CheckoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addContainerGap()));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(12, 12, 12).addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(StoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 562,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CheckoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void ApplyCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
                // TODO add your handling code here:
                CalcPrc();
        }// GEN-LAST:event_jButton8ActionPerformed

        private void StoreBtnActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                myStorePage.setVisible(true);
        }// GEN-LAST:event_jButton2ActionPerformed

        private void CheckoutBtnActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                myStorePage.setVisible(true);
                CartItemsPanel.removeAll();
                myCartList.clear();
                myStorePage.MyCartBtn.setText("My Cart");
                loadItems();

              
        }// GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(final String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (final ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (final InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (final IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MyCart().setVisible(true);
                        }
                });
        }

        public void loadItems() {
                GridLayout CartItemsPanelLayout = new GridLayout(0, 1);
                CartItemsPanelLayout.setVgap(10);

                CartItemsPanel.setLayout(CartItemsPanelLayout);

                CartItemsPanel.removeAll();

                // System.out.println(sum);
                CalcPrc();
                myCartList.forEach(item -> {
                        final CartItemPanel firstItem = new CartItemPanel(item, myCartList, myStorePage);
                        firstItem.ParentFrame = this;
                        CartItemsPanel.add(firstItem);
                });
                CartItemsPanel.revalidate();
                CartItemsPanel.repaint();

        }

        public void CalcPrc() {
                double sum = 0;

                for (StoreItem itm : myCartList) {
                        sum += itm.Price * itm.Unit;
                }
                double discount = 1;
                TotalPrcLble.setText(sum + " RM");
                if (PromoTextField.getText().trim().equals("STORE50")) {
                        discount = 0.5;
                }
                if (PromoTextField.getText().trim().equals("STORE30")) {
                        discount = 0.7;
                }
                if (PromoTextField.getText().trim().equals("STORE10")) {
                        discount = 0.9;
                }
                double finalPrice = sum * discount;
                FnlPriceLble.setText(finalPrice + " RM");

        }

        public MainPage myStorePage;
        public LinkedList<StoreItem> myCartList;

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ApplyCodeBtn;
        private javax.swing.JPanel CartItemsPanel;
        private javax.swing.JButton CheckoutBtn;
        private javax.swing.JLabel FnlPriceLble;
        private javax.swing.JScrollPane JScroll1;
        private javax.swing.JTextField PromoTextField;
        private javax.swing.JButton StoreBtn;
        private javax.swing.JLabel TotalPrcLble;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        // End of variables declaration//GEN-END:variables
}

class CartItemPanel extends javax.swing.JPanel {
        /**
         *
         */
        private static final long serialVersionUID = 1L;
        JButton DeleteFromCartBtn = new JButton(); // jButton12
        JLabel ProductNameLbl = new JLabel(); // jLabel28
        JLabel PriceLbl = new JLabel();// jLabel29
        JSpinner CounterSpin;
        JPanel PicturePnl = new JPanel(); // jPanel8
        StoreItem storeItem;
        public LinkedList<StoreItem> myCartList;
        public MyCart ParentFrame;
        MainPage myStorePage;

        CartItemPanel(final StoreItem _storeItem, final LinkedList<StoreItem> _myCartList, MainPage _myStorePage) {
                super();
                storeItem = _storeItem;
                myCartList = _myCartList;
                myStorePage = _myStorePage;
                SpinnerNumberModel model1 = new SpinnerNumberModel(1, 0, 10, 1);
                CounterSpin = new JSpinner(model1);

                this.setBackground(new java.awt.Color(255, 255, 255));
                // panel size
                this.setPreferredSize(new java.awt.Dimension(200, 150));
                ProductNameLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                ProductNameLbl.setText(storeItem.Name);

                PriceLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                PriceLbl.setText(storeItem.Price + " RM");

                CounterSpin.setValue(storeItem.Unit);
                DeleteFromCartBtn.setText("Delete from Cart");

                setItemsLayout();

        }

        void setItemsLayout() {
                final javax.swing.GroupLayout PicturePnlLayout = new javax.swing.GroupLayout(PicturePnl);
                PicturePnl.setLayout(PicturePnlLayout);
                PicturePnlLayout.setHorizontalGroup(
                                PicturePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 119, Short.MAX_VALUE));
                PicturePnlLayout.setVerticalGroup(
                                PicturePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 118, Short.MAX_VALUE));
                // jPanel18
                final javax.swing.GroupLayout CartItemPanelLayout = new javax.swing.GroupLayout(this);
                this.setLayout(CartItemPanelLayout);

                CartItemPanelLayout.setHorizontalGroup(CartItemPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CartItemPanelLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(PicturePnl, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33).addComponent(ProductNameLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98,
                                                                Short.MAX_VALUE)
                                                .addComponent(PriceLbl).addGap(68, 68, 68)
                                                .addComponent(CounterSpin, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(DeleteFromCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)));
                CartItemPanelLayout.setVerticalGroup(CartItemPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CartItemPanelLayout.createSequentialGroup().addGroup(CartItemPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(CartItemPanelLayout.createSequentialGroup().addGap(41, 41, 41)
                                                                .addGroup(CartItemPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(ProductNameLbl)
                                                                                .addComponent(PriceLbl)
                                                                                .addComponent(DeleteFromCartBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                39,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(CounterSpin,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(CartItemPanelLayout.createSequentialGroup().addContainerGap()
                                                                .addComponent(PicturePnl,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap()));

                DeleteFromCartBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(final java.awt.event.ActionEvent evt) {
                                deleteItemfromCartOnClick(evt);
                        }
                });
                CounterSpin.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                CounterSpinChanged(evt);
                        }
                });

        }

        private void deleteItemfromCartOnClick(final java.awt.event.ActionEvent evt) {
                final int index = myCartList.indexOf(storeItem);
                myCartList.remove(index);
                ParentFrame.loadItems();

                myStorePage.MyCartBtn
                                .setText("My Cart " + (myCartList.size() > 0 ? "[" + myCartList.size() + "]" : ""));
        }

        private void CounterSpinChanged(javax.swing.event.ChangeEvent evt) {
                storeItem.Unit = (Integer) CounterSpin.getValue();
                ParentFrame.loadItems();
        }

}
